// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbzzrgjurcjbnqatuxaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtienpyZ2p1cmNqYm5xYXR1eGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTgzODEsImV4cCI6MjA2NzM3NDM4MX0.k7PIsp_OgAmghm55oWpWHhsNGmeH4ttdqbG5G0w9iNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});